project:
  type: website
  output-dir: docs

website:
  title: "travisrutledge"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/travisrutledge
      - icon: linkedin
        href: https://www.linkedin.com/in/travisrutledge/
     
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

